In [ ]:
stats = [
    {
        'movie': 'На странных берегах',
        'bodycount': {'люди': 56, 'русалки': 2, 'ядовитые жабы': 3, 'пираты-зомби': 2}
    },
    {
        'movie': 'На краю света',
        'bodycount': {'люди': 88}
    },
    {
        'movie': 'Сундук мертвеца',
        'bodycount': {'люди': 56, 'крабы отшельники': 1}
    },
    {
        'movie': 'Проклятие Черной жемчужины',
        'bodycount': {'люди': 17}
    },
]
summ = 0
count = 0
for el in stats:
    summ+=el['bodycount']['люди']

print(round(summ/ len(stats)))



### Numpy и матричная алгебра

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])


In [ ]:
type(x)

In [ ]:
x.mean()




In [ ]:
print(x+y)
print(x-y)

In [ ]:
x-y


In [ ]:
print(x**y)
print(x%y)

##### Автоматеческое наполнение массивов

In [ ]:
# аналог range
print(np.arange(10))
# матрица 10 заполненная 5
print(np.full(10,5))
# матрица 2 на 5 заполненная 5
print(np.full([2, 5], 5))

In [ ]:
# объеденить массивы
a= np.arange(10)
print(a)
b= np.arange(10,20)
print(b)
np.concatenate((a, b))

In [ ]:
# перемешать элементы массива
import random
a = np.arange(10)
random.shuffle (a)
a

In [ ]:
### Упражнение
# По мотивам https://thecode.media/choose-life/
#
# По результатам собеседования вам предлагают определенную зарплату. И конверт, который может случайным образом снизить или увеличить эту зарплату вдвое. Т. е. если сначала была сумма Х, то после вскрытия конверта она может стать 0.5Х или 2Х. Как в среднем изменится будущая зарплата, если соискатель решил открыть конверт?
#
# Смоделируйте процесс изменения условной зарплаты в 1000 в случае открытия конверта:
# 1. Задайте переменную n_samples = 1000
# 2. Создайте numpy array из n_samples элементов, равных зарплате 0.5Х. И такой же с зарплатой 2Х.
# 3. Объедините их в один массив
# 4. Перемешайте значения в получившемся массиве
# 5. Посчитайте среднее значение зарплаты для объединенного массива

n_samples = 1000
array1 = np.full(1000,1000*0.5)
array2 = np.full(1000,1000*2)
array = np .concatenate ((array1,array2))
random.shuffle(array)
array.mean()

In [42]:
# Измение размерности

x = np.arange(0,10)
a= x
print(a.shape)
x= x.reshape(5,2)
print(x)
print(x.shape)

# Измение размерности ТРАНСПОНИРОВНИМЕ
x.T

(10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [48]:
# склеиваине массивов
x = np.array([[1,2,3,4], [2,3,4,6]])
print(x.ravel())

[list([2, 3, 4]) list([2, 3, 4, 6])]


c:\python37\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


#### Создание матриц

In [52]:
# нулевой вектор заданной размерности
np.zeros(2)

array([0., 0.])

In [67]:
# единичная матрица

np.eye(5)

# более общий случай диагональной матрицы
np.diag(np.arange(2, 50, 15), k=-5)


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 17,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 32,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 47,  0,  0,  0,  0,  0]])

In [69]:
# матрица со случайными значениями

np.random.random(10)

np.linspace(1,17,10)

array([ 1.        ,  2.77777778,  4.55555556,  6.33333333,  8.11111111,
        9.88888889, 11.66666667, 13.44444444, 15.22222222, 17.        ])

In [77]:
# Дана единичная матрица np.eye(10). Посчитайте сумму ее диагональных элементов.
a = np.eye(11)
print(sum(np.diagonal(a)))

11.0


#### Скалярное произведение векторов
\begin{equation*}
\LARGE
\vec{a} \dot{} \vec{b} = |\vec{a}| \space |\vec{b}| \space cos(\vec{a}, \vec{b})
\end{equation*}